apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: python-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-webapp
  template:
    metadata:
      labels:
        app: python-webapp
    spec:
      containers:
        - name: python-webapp
          image: python-webapp:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: development