apiVersion: v1
kind: Service
metadata:
  name: python-webapp
spec:
  type: NodePort
  selector:
    app: python-webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30002